### PR TITLE
Adds support for webpack 3

### PR DESCRIPTION
**Pull request by oayres**
Tiny syntax tweak so we can use this in new projects.

If possible, can we push to npm too? I _hope_ this is still maintained enough to approve this PR :)

### CODE REVIEW

**Comment by ruscoder** [comment]
Hello @oayres! Thank you for your contribution. But we don't use and support this repository. I can grant you permission for npm if you want to support it.

**Comment by oayres** [comment]
Hey @ruscoder. It is sad to hear this is no longer maintained! If you could grant me permission on npm to maintain this, that'd be ace. My npm user is **owen.a**.

Thanks for getting back to us.

**Comment by ruscoder** [comment]
@oayres I've added you as an owner
https://www.npmjs.com/package/webpack-polyfills-plugin

**Comment by oayres** [comment]
@ruscoder thanks mate. Would you be able to update the readme on your repo to let others know the ownership has transferred to https://github.com/oayres/webpack-polyfills-plugin please?

For anybody reading this, the npm package will be updated with this PR by the time you read this.

Please submit all future PRs to this repo: https://github.com/oayres/webpack-polyfills-plugin

**Comment by ruscoder** [comment]
@oayres Ok, @ir4y will accept this PR soon.

**Pull request merged**
